import type { Metadata } from "next";
import Footer from "@/component/layout/common/Footer";
import Navigation from "@/component/layout/common/Navigation";

import "./globals.css";
export const metadata: Metadata = {
  title: "Secret City - Adventure | Escape Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center bg-gray-700 min-h-screen">
        <div className="w-full sm:w-full md:w-1/3 lg:w-2/8">
          <main className="h-screen flex flex-col shadow-lg bg-gray-50">
            <Navigation />
            <div className="h-screen overflow-y-auto">
            {children}
            </div>
            <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}
